# Generated by Django 6.0.2 on 2026-02-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_options_and_more'),
        ('courses', '0016_alter_feepayment_bank_slip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assignmentavailability',
            options={'verbose_name_plural': 'Assignment Availabilities'},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentavailability',
            unique_together={('assignment', 'cohort')},
        ),
    ]
