# Generated by Django 6.0.2 on 2026-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_exam',
            field=models.BooleanField(default=False, help_text='Check if this assignment should be treated as an Exam (higher priority display).'),
        ),
    ]
