# Generated by Django 6.0.2 on 2026-02-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_is_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sort_key',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
