# Generated by Django 6.0.2 on 2026-02-17 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_and_more'),
        ('courses', '0015_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.module'),
        ),
    ]
