# Generated by Django 6.0.2 on 2026-02-18 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_module'),
        ('courses', '0015_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='allow_late',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
        migrations.CreateModel(
            name='AssignmentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('allow_late', models.BooleanField(default=False)),
                ('late_until', models.DateTimeField(blank=True, null=True)),
                ('reopen_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='assignments.assignment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_availabilities', to='courses.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
