# Generated by Django 5.2.12 on 2026-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_alter_assignment_id_alter_assignmentavailability_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentavailability',
            name='late_penalty',
            field=models.FloatField(default=0.0, help_text='Percentage penalty for late submission (e.g. 10.0 for 10% reduction).'),
        ),
    ]
