# Generated by Django 6.0.2 on 2026-02-14 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_cohort_course_cohort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='assigned_cohorts', to=settings.AUTH_USER_MODEL),
        ),
    ]
