# Generated by Django 6.0.2 on 2026-02-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_feepayment_phone_number_feepayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason for rejection or admin notes'),
        ),
    ]
