# Generated by Django 6.0.2 on 2026-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_feepayment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
