# Generated by Django 6.0.2 on 2026-02-16 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_enrollment_cohort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_link', models.URLField(max_length=500)),
                ('meeting_password', models.CharField(blank=True, max_length=100)),
                ('moderator_link', models.URLField(blank=True, help_text='Link for lecturers only', max_length=500)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('recording_shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='courses.cohort')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
