# Generated by Django 6.0.2 on 2026-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_onlinemeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinemeeting',
            name='moderator_link',
        ),
        migrations.AlterField(
            model_name='onlinemeeting',
            name='meeting_password',
            field=models.CharField(max_length=100),
        ),
    ]
