# Generated by Django 6.0.2 on 2026-02-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_onlinemeeting_moderator_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='bank_slip',
            field=models.FileField(blank=True, help_text='Upload bank slip (JPG or PDF)', null=True, upload_to='bank_slips/'),
        ),
    ]
