# Generated by Django 6.0.2 on 2026-02-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of class in minutes'),
        ),
    ]
