# Generated by Django 6.0.2 on 2026-02-17 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_onlinemeeting_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_attended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='onlinemeeting',
            name='meeting_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['meeting', 'student', 'is_attended'], name='courses_att_meeting_e25b46_idx'),
        ),
    ]
