# Generated by Django 6.0.2 on 2026-02-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='bank_slip',
            field=models.FileField(blank=True, help_text='Upload bank slip (JPG or PDF)', max_length=255, null=True, upload_to='bank_slips/'),
        ),
        migrations.AlterField(
            model_name='onlinemeeting',
            name='recording_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='recordings/'),
        ),
    ]
