# Generated by Django 5.2.12 on 2026-03-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_enrollment_manual_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
