"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-atc$3*&bh#c3g!omq3b7#6ctlstq+4lhq@$o48kp71b)hnua^q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Email Backend for Development (Console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'LMS System <noreply@lms.com>'


# Application definition

INSTALLED_APPS = [
    # Django default apps
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local apps
    "accounts",  # Make sure this is added
    "courses",
    "assignments",
    "submissions",
    "grading",
    "approvals",
    "audit",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.CohortAccessMiddleware',
]

ROOT_URLCONF = 'config.urls'

import os

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.admin_notifications",
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# CORS (allow frontend later)
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework (JWT later)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Media uploads (pdf, images, pka)
import os
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DATA_UPLOAD_MAX_MEMORY_SIZE = 262144000  # 250MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 262144000  # 250MB

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Session settings to improve user switching
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # 1 hour

JAZZMIN_SETTINGS = {
    "site_title": "LMS Admin",
    "site_header": "LMS Administration",
    "site_brand": "LMS",
    "welcome_sign": "Welcome to LMS Admin",
    "copyright": "LMS",

    "show_sidebar": True,
    "show_ui_builder": False,
    "navigation_expanded": True,

    "icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "accounts.User": "fas fa-user-shield",
        "courses.Cohort": "fas fa-layer-group",
        "courses.Course": "fas fa-book",
        "courses.Enrollment": "fas fa-user-graduate",
        "assignments.Assignment": "fas fa-tasks",
        "submissions.Submission": "fas fa-file-upload",
    },

   # top menu links (always show LMS Login + Logout)
"topmenu_links": [
    {"name": "Dashboard", "url": "admin:index"},

    {"name": "Main Site", "url": "/", "new_window": True},

    # Logs out of LMS (accounts)
    {"name": "LMS Logout", "url": "/accounts/logout/", "new_window": False},

    # Logs out of Django Admin
    {"name": "Admin Logout", "url": "admin:logout"},
],

    "order_with_respect_to": [
        "accounts",
        "courses",
        "assignments",
        "submissions",
        "approvals",
    ],

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "accounts.user": "horizontal_tabs",
        "auth.user": "horizontal_tabs",
    },
    "custom_css": "css/admin_tweaks.css",
    "custom_js": "js/admin_tabs_fix.js",

    "custom_links": {
        "accounts": [{
            "name": "Main Dashboard",
            "icon": "fas fa-home",
            "url": "/",
        }]
    },

}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",         # ✅ dark modern theme
    "dark_mode_theme": "darkly",
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
}





