# Generated by Django 6.0.2 on 2026-02-13 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_and_more'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='submissionfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='is_locked',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='score',
            new_name='marks_awarded',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'assignment')},
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='graded_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
    ]
