# Generated by Django 6.0.2 on 2026-02-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_last_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='last_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
