"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from dotenv import load_dotenv

# Load .env file
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-atc$3*&bh#c3g!omq3b7#6ctlstq+4lhq@$o48kp71b)hnua^q')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'ciscocanvas.chuka.ac.ke,*').split(',')
X_FRAME_OPTIONS = 'SAMEORIGIN'

CSRF_TRUSTED_ORIGINS = [
    "https://ciscocanvas.chuka.ac.ke",
    "https://nonsubsiding-bernard-unneural.ngrok-free.dev",
    "https://ding-bernard-unneural.ngrok-free.dev",
    "https://cold-lines-search.loca.lt",
    "https://gold-ants-leave.loca.lt",
    "https://cytoplast-capillary-spearfish.ngrok-free.dev",
    "https://chuka-cisco-portal.loca.lt",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Email Configuration (SMTP via Brevo)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'a4aa06001@smtp-brevo.com'
EMAIL_HOST_PASSWORD = 'bsk5DEVQB2NGcrC'
DEFAULT_FROM_EMAIL = 'Chuka University CUCCNA Academy <cisco@chuka.ac.ke>'


# Application definition

INSTALLED_APPS = [
    # Django default apps
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local apps
    "accounts",  # Make sure this is added
    "courses",
    "assignments",
    "submissions",
    "grading",
    "approvals",
    "audit",
    "communications",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.CohortAccessMiddleware',
    'audit.middleware.AuditLogMiddleware',
]

ROOT_URLCONF = 'config.urls'

import os

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": False,  # Must be False when loaders is defined
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.admin_notifications",
                "communications.context_processors.unread_messages",
            ],
            "loaders": [
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 600,  # 10 minutes of persistent connection
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# CORS (allow frontend later)
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework (JWT later)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Media uploads (pdf, images, pka)
import os
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DATA_UPLOAD_MAX_MEMORY_SIZE = 262144000  # 250MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 262144000  # 250MB

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Session settings to improve user switching
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # 1 hour

JAZZMIN_SETTINGS = {
    "site_title": "CISCO Network Academy Admin",
    "site_header": "CISCO Network Academy Admin",
    "site_brand": "CHUKA UNIVERSITY CISCO Network Academy",
    "welcome_sign": "Welcome to CHUKA UNIVERSITY CISCO Network Academy",
    "copyright": "CHUKA UNIVERSITY CISCO Network Academy",

    "show_sidebar": True,
    "show_ui_builder": False,
    "navigation_expanded": True,

    "icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "accounts.User": "fas fa-user-shield",
        "courses.Cohort": "fas fa-layer-group",
        "courses.Course": "fas fa-book",
        "courses.Enrollment": "fas fa-user-graduate",
        "assignments.Assignment": "fas fa-tasks",
        "submissions.Submission": "fas fa-file-upload",
    },

   # top menu links (always show LMS Login + Logout)
"topmenu_links": [
    {"name": "Dashboard", "url": "admin:index"},

    {"name": "Audit Dashboard", "url": "/audit/logs/", "new_window": False},

    {"name": "Main Site", "url": "/", "new_window": True},

    # Logs out of Chuka University CUCCNA Academy
    {"name": "Logout", "url": "/accounts/logout/", "new_window": False},

    # Logs out of Django Admin
    {"name": "Admin Logout", "url": "admin:logout"},
],

    "order_with_respect_to": [
        "accounts",
        "courses",
        "assignments",
        "submissions",
        "approvals",
    ],

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "accounts.user": "horizontal_tabs",
        "auth.user": "horizontal_tabs",
    },
    "custom_js": "js/admin_tabs_fix.js",
    "custom_css": "css/admin_tweaks.css",

    "custom_links": {
        "accounts": [{
            "name": "Main Dashboard",
            "icon": "fas fa-home",
            "url": "/",
        }]
    },

}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",         # ✅ dark modern theme
    "dark_mode_theme": "darkly",
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
}

# --- Performance Optimizations ---

# Memory Cache (Local-memory for rapid access)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Optimized Template Loading (Cached on production-like environments)
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]





DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
