# Generated by Django 6.0.2 on 2026-02-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
