# Generated by Django 6.0.2 on 2026-02-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_submission_assignment_remove_grade_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], default='STUDENT', max_length=20),
        ),
    ]
