# Generated by Django 6.0.2 on 2026-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
