# Generated by Django 6.0.2 on 2026-02-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
