# Generated by Django 5.2.12 on 2026-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='transcript_lock_override',
            field=models.CharField(choices=[('AUTO', 'Automatic (System Rules)'), ('LOCKED', 'Manual: Always Locked'), ('UNLOCKED', 'Manual: Always Unlocked')], default='AUTO', help_text='Override system rules for Transcript downloads', max_length=20),
        ),
    ]
