# Generated by Django 5.2.12 on 2026-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_assignmentapproval_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
