# Generated by Django 6.0.2 on 2026-02-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_feepayment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.cohort'),
        ),
    ]
