# Generated by Django 5.2.12 on 2026-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_enrollment_certificate_lock_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='manual_certificate',
            field=models.FileField(blank=True, help_text='Upload a custom certificate (PDF/JPG/PNG) to bypass automated generation', null=True, upload_to='certificates/manual/'),
        ),
    ]
