# Generated by Django 5.2.12 on 2026-03-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_enrollment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
    ]
