# Generated by Django 6.0.2 on 2026-02-20 21:30

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_approved_at_submission_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=submissions.models.submission_upload_path),
        ),
    ]
