# Generated by Django 6.0.2 on 2026-02-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submissionfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
