# Generated by Django 6.0.2 on 2026-02-16 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofile_registration_number_and_more'),
        ('courses', '0007_feepayment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.cohort'),
        ),
    ]
