# Generated by Django 6.0.2 on 2026-02-16 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='new_password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
